"""
OCR Engine for MediLens-360
Uses Google Gemini Flash/Pro Vision for high-accuracy handwriting recognition and structured extraction.
"""

import google.generativeai as genai
from PIL import Image
import io
import os
import json
import sys
from dotenv import load_dotenv

load_dotenv()

# Configure Gemini
GOOGLE_API_KEY = os.getenv("GOOGLE_API_KEY")
if GOOGLE_API_KEY:
    genai.configure(api_key=GOOGLE_API_KEY)
else:
    print("WARNING: GOOGLE_API_KEY not found. OCR will fail.", file=sys.stderr)

def extract_text_from_image(image_bytes: bytes) -> str:
    """
    This function is kept for compatibility but now returns a JSON string 
    generated by Gemini, or a raw text description if JSON fails.
    """
    if not GOOGLE_API_KEY:
        return '{ "error": "Missing GOOGLE_API_KEY" }'

    try:
        print(f"[OCR] Starting Gemini Vision extraction...", file=sys.stderr)
        image = Image.open(io.BytesIO(image_bytes))
        
        model = genai.GenerativeModel('gemini-flash-latest')
        
        prompt = """
        You are an expert pharmacist helper. 
        Analyze this prescription image and extract the medicines, their dosages, and frequencies.
        
        Strictly determine if the image is a valid medical prescription (doctor's note, medicine packaging, or pharmacy receipt).
        - If it is NOT a prescription (e.g., a random photo, a selfie, a landscape, a non-medical document), set "is_prescription" to false.
        
        Return ONLY a JSON object with this exact structure:
        {
          "is_prescription": true/false,
          "validation_message": "If not a prescription, return EXACTLY: 'The uploaded image is not a valid medical prescription. Please upload a clear photo of a doctor's prescription.' If it is valid, return 'Valid prescription'.",
          "raw_text": "The full text visible on the image",
          "medicines": [
            {
              "name": "Medicine Name",
              "dosage": "500mg (or whatever is written)",
              "frequency": "BD/Twice daily (interpret abbreviations)",
              "original_text": "The exact line related to this medicine"
            }
          ]
        }
        Do not include markdown formatting (like ```json). Just the raw JSON.
        If the image is not a prescription or contains no medicines, return an empty medicines list and set is_prescription to false.
        """
        
        response = model.generate_content([prompt, image])
        
        if response.usage_metadata:
            print(f"\n[OCR Token Usage] Input: {response.usage_metadata.prompt_token_count}, Output: {response.usage_metadata.candidates_token_count}, Total: {response.usage_metadata.total_token_count}", file=sys.stderr)

        text_response = response.text.replace('```json', '').replace('```', '').strip()
        
        print(f"[OCR] Gemini Response length: {len(text_response)}", file=sys.stderr)
        return text_response
        
    except Exception as e:
        print(f"[OCR] Error calling Gemini: {e}", file=sys.stderr)
        return json.dumps({
            "error": str(e),
            "raw_text": "Error processing image",
            "medicines": []
        })

def parse_prescription_text(text: str) -> dict:
    """
    Parses the response from extract_text_from_image.
    Since Gemini now returns JSON string, we just parse it.
    """
    try:
        data = json.loads(text)
        
        # Ensure the structure matches what frontend expects
        return {
            "is_prescription": data.get("is_prescription", False),
            "validation_message": data.get("validation_message", "Unknown validation status"),
            "raw_text": data.get("raw_text", ""),
            "medicines": data.get("medicines", []),
            "total_lines_processed": 0, # Legacy field
            "medicines_found": len(data.get("medicines", []))
        }
    except json.JSONDecodeError:
        # Fallback if Gemini returned plain text instead of JSON
        return {
            "is_prescription": False,
            "validation_message": "Failed to parse API response. Please try again.",
            "raw_text": text,
            "medicines": [],
            "error": "Failed to parse API response as JSON"
        }

